version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build_and_test:
    jobs:
      - cypress/run:
         build: "npm run build"
         record: true
         parallel: true
         parallelism: 8